version: '3.8'
services:
  spring-app:
    image: myapp
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080"
    deploy:
      replicas: 3
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring-app

